export enum LocationCategory {
  AGRICULTURE = "agriculture",
  BUILDING = "building",
  COMMERCE = "commerce",
  CONSTRUCTION = "construction",
  EDUCATION = "education",
  FICTITIOUS = "fictitious",
  FINANCIAL = "financial",
  GOVERNMENT = "government",
  HEALTH = "health",
  INDUSTRIAL = "industrial",
  MILITARY = "military",
  NATURAL_WATER = "natural/water",
  OUTDOORS_RECREATION = "outdoors/recreation",
  PLACE = "place",
  PLACE_OF_WORSHIP = "place_of_worship",
  POSTCODE = "postcode",
  ROAD = "road",
  SOCIAL = "social",
  TRANSPORTATION = "transportation",
  TRAVEL_TOURISM = "travel/tourism",
  UNKNOWN = "unknown",
}
